spring.datasource.url=jdbc:postgresql://ep-falling-unit-ad50zceo-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yAuwv76MPxsL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

frontend.url=https://scintillating-alpaca-716c3a.netlify.app

server.port=${PORT:8080}

jwt.secret=7f8c9a1b2d3e4f5a6b7c8d9e
jwt.expiration=3600000